### ISSUE TITLE
RevitBaseImported parameter

### ISSUE THREAD

**Issue by kelyamany** [sanderobdeijn/RevitMSBuildTargets#1]
Thank you @sanderobdeijn a lot for this brilliant solution, it helped me a lot.

I would like to point to a small typo with these checks:

https://github.com/sanderobdeijn/RevitMSBuildTargets/blob/9eefdef7669ed7b10497f267075fd26949491970/Targets/Revit.AdWindows.targets#L2

https://github.com/sanderobdeijn/RevitMSBuildTargets/blob/9eefdef7669ed7b10497f267075fd26949491970/Targets/Revit.RevitAPI.targets#L2

https://github.com/sanderobdeijn/RevitMSBuildTargets/blob/9eefdef7669ed7b10497f267075fd26949491970/Targets/Revit.RevitAPIUI.targets#L2

I think it won't display importing duplication errors if we replaced them with this line instead:
`<Import Condition="$(RevitBaseImported) != 'true'" Project="Revit.Base.targets" />`

**Comment by sanderobdeijn** [comment]
Thank you for this issue, I already noticed this issue and fixed it. But I saw I forgot to push it. Could you test it now?
